Partner.create!([{ name: "Mark", phone_number: 9104689402, industry: "Fintech", problem: "Solve", customer: "Millenials" } ])
Partner.create!([{ name: "Johnie", phone_number: 9773345108, industry: "Fintech", problem: "Solve", customer: "Baby boomers" } ])
Partner.create!([{ name: "Jacob", phone_number: 9455239895, industry: "Fintech", problem: "Solve", customer: "Everyone" } ])
Partner.create!([{ name: "Han", phone_number: 9668132471, industry: "Fintech", problem: "Create", customer: "Millenials" } ])
Partner.create!([{ name: "Yuan", phone_number: 9326863048, industry: "Fintech", problem: "Create", customer: "Baby boomers" } ])
Partner.create!([{ name: "Janice", phone_number: 9668132471, industry: "Fintech", problem: "Create", customer: "Everyone" } ])
Partner.create!([{ name: "Henry", phone_number: 9603158786, industry: "Healthcare/biotech", problem: "Solve", customer: "Millenials" } ])
Partner.create!([{ name: "Mohammed", phone_number: 9806473571, industry: "Healthcare/biotech", problem: "Solve", customer: "Baby boomers" } ])
Partner.create!([{ name: "Xenia", phone_number: 9978413951, industry: "Healthcare/biotech", problem: "Solve", customer: "Everyone" } ])
Partner.create!([{ name: "Jian", phone_number: 9838537399, industry: "Healthcare/biotech", problem: "Create", customer: "Millenials" } ])
Partner.create!([{ name: "Ashwarya", phone_number: 9237451368, industry: "Healthcare/biotech", problem: "Create", customer: "Baby boomers" } ])
Partner.create!([{ name: "Linyi", phone_number: 9493548771, industry: "Healthcare/biotech", problem: "Create", customer: "Everyone" } ])
Partner.create!([{ name: "Kedi", phone_number: 9622483431, industry: "Data and Analytics", problem: "Solve", customer: "Millenials" } ])
Partner.create!([{ name: "Ranjit", phone_number: 9296635205, industry: "Data and Analytics", problem: "Solve", customer: "Baby boomers" } ])
Partner.create!([{ name: "Bonnie", phone_number: 9110093366, industry: "Data and Analytics", problem: "Solve", customer: "Everyone" } ])
Partner.create!([{ name: "Manchit", phone_number: 9491238088, industry: "Data and Analytics", problem: "Create", customer: "Millenials" } ])
Partner.create!([{ name: "Megan", phone_number: 9734830029, industry: "Data and Analytics", problem: "Create", customer: "Baby boomers" } ])
Partner.create!([{ name: "Meng", phone_number: 9690966105, industry: "Data and Analytics", problem: "Create", customer: "Everyone" } ])
Partner.create!([{ name: "Hua", phone_number: 9560470431, industry: "consumer goods", problem: "Solve", customer: "Millenials" } ])
Partner.create!([{ name: "Kira", phone_number: 9463735114, industry: "consumer goods", problem: "Solve", customer: "Baby boomers" } ])
Partner.create!([{ name: "Sheng", phone_number: 9519945811, industry: "consumer goods", problem: "Solve", customer: "Everyone" } ])
Partner.create!([{ name: "Yang", phone_number: 9568199346, industry: "consumer goods", problem: "Create", customer: "Millenials" } ])
Partner.create!([{ name: "Nandita", phone_number: 9891245145, industry: "consumer goods", problem: "Create", customer: "Baby boomers" } ])
Partner.create!([{ name: "Olivia", phone_number: 9541686141, industry: "consumer goods", problem: "Create", customer: "Everyone" } ])
Partner.create!([{ name: "Xi", phone_number: 9484195362, industry: "Education", problem: "Solve", customer: "Millenials" } ])
Partner.create!([{ name: "Ash", phone_number: 9729233837, industry: "Education", problem: "Solve", customer: "Baby boomers" } ])
Partner.create!([{ name: "Ashley", phone_number: 9234174757, industry: "Education", problem: "Solve", customer: "Everyone" } ])
Partner.create!([{ name: "Shrey", phone_number: 9103222993, industry: "Education", problem: "Create", customer: "Millenials" } ])
Partner.create!([{ name: "Vanessa", phone_number: 9821885005, industry: "Education", problem: "Create", customer: "Baby boomers" } ])
Partner.create!([{ name: "Violet", phone_number: 9785263402, industry: "Education", problem: "Create", customer: "Everyone" } ])
Partner.create!([{ name: "Ben", phone_number: 9852769471, industry: "Energy", problem: "Solve", customer: "Millenials" } ])
Partner.create!([{ name: "Chelsie", phone_number: 9431709294, industry: "Energy", problem: "Solve", customer: "Baby boomers" } ])
Partner.create!([{ name: "Cansu", phone_number: 9455694842, industry: "Energy", problem: "Solve", customer: "Everyone" } ])
Partner.create!([{ name: "Swagata", phone_number: 9710008869, industry: "Energy", problem: "Create", customer: "Millenials" } ])
Partner.create!([{ name: "Vignesh", phone_number: 9586504862, industry: "Energy", problem: "Create", customer: "Baby boomers" } ])
Partner.create!([{ name: "Xiaolin", phone_number: 9424246381, industry: "Energy", problem: "Create", customer: "Everyone" } ])
Partner.create!([{ name: "Corey", phone_number: 9138143169, industry: "Transportation", problem: "Solve", customer: "Millenials" } ])
Partner.create!([{ name: "Hongyu", phone_number: 9748087952, industry: "Transportation", problem: "Solve", customer: "Baby boomers" } ])
Partner.create!([{ name: "Isabelle", phone_number: 9104660156, industry: "Transportation", problem: "Solve", customer: "Everyone" } ])
Partner.create!([{ name: "Woo", phone_number: 9193228812, industry: "Transportation", problem: "Create", customer: "Millenials" } ])
Partner.create!([{ name: "Ching", phone_number: 9402620544, industry: "Transportation", problem: "Create", customer: "Baby boomers" } ])
Partner.create!([{ name: "Shin", phone_number: 9782177046, industry: "Transportation", problem: "Create", customer: "Everyone" } ])
